/**
 * Project-global vocabulary for the budget workbench.
 *
 * This file is an ambient declaration: it has no imports or exports, so every
 * type below is visible project-wide without wiring. It exists so `core`, `cli`
 * and `webapp` talk about the domain with the same words.
 *
 * - `core` owns the domain model and persistence (`core/src/schemas`, `core/src/stores`).
 * - `cli` exposes that model to other programs (scriptable, JSON output).
 * - `webapp` visualizes the same data in a UI.
 *
 * These declarations mirror the shapes in `core/src/schemas/` and
 * `core/src/stores/types.ts`. Modules keep their own detailed types; this file
 * only names the shared concepts. It is documentation, not an integration:
 * nothing imports it and no build depends on it.
 */

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

/**
 * A signed amount of money, in whole cents.
 *
 * Money is *always* integer cents in this project — never floating-point
 * dollars — so that arithmetic on balances is exact. Dollars appear only at the
 * edges, for input parsing and display (`dollarsToCents`, `centsToDollars`,
 * `formatCurrency` in `core/src/schemas/transaction.ts`).
 *
 * The sign carries meaning: **positive is an inflow** (money arriving, income,
 * a refund) and **negative is an outflow** (spending). The same convention
 * applies to derived sums such as a category's activity for a month.
 *
 * @example -1250 // $12.50 spent
 */
type Cents = number

/**
 * An ISO 8601 calendar date, `YYYY-MM-DD`, with no time or timezone component.
 *
 * Used for things that happen on a day rather than at an instant — a
 * transaction's date, a target's deadline. Because the format is fixed-width
 * and zero-padded, lexical string comparison is also chronological order, which
 * is how date range filters are implemented.
 *
 * @example '2025-01-15'
 */
type IsoDate = string

/**
 * A full ISO 8601 timestamp, as produced by `Date#toISOString()`.
 *
 * Used for machine bookkeeping — when a record was last recomputed, when an
 * export was taken — as opposed to a date the user chose. Distinct from
 * {@link IsoDate}, which never carries a time.
 *
 * @example '2025-01-15T09:30:00.000Z'
 */
type IsoDateTime = string

/**
 * A unique identifier for an entity: a UUID generated by `crypto.randomUUID()`.
 *
 * Every entity owns one, and relationships are expressed by storing another
 * entity's `Uuid` (`accountId`, `categoryId`, `payeeId`, …) rather than by
 * nesting objects. IDs are opaque — never parse them or infer ordering.
 */
type Uuid = string

/**
 * A budgeting period key: a single month, `YYYY-MM`.
 *
 * The month is the unit of planning. Money is assigned per month, categories
 * carry a balance forward from one month to the next, and summaries close out a
 * month. Like {@link IsoDate}, the format sorts lexically in chronological
 * order, which the month-navigation helpers rely on.
 *
 * @example '2025-01'
 */
type Month = string

/**
 * An ISO 4217 currency code, used for display formatting only.
 *
 * The project stores {@link Cents} without a currency tag; the code lives on the
 * {@link Budget} and every amount within that budget is denominated in it.
 *
 * @example 'USD'
 */
type CurrencyCode = string

// ---------------------------------------------------------------------------
// Fixed domain vocabularies
// ---------------------------------------------------------------------------

/**
 * The kind of financial container an {@link Account} represents.
 *
 * The distinction that matters for budgeting is on-budget versus tracking:
 * `checking`, `savings`, `credit` and `cash` hold money that can be assigned to
 * categories, while `tracking` covers balances you want visible but do not
 * budget (investments, property, loans).
 */
type AccountType = 'checking' | 'savings' | 'credit' | 'cash' | 'tracking'

/**
 * The shape of a category's goal — how a {@link Target} should be read.
 *
 * - `spending_limit` — a ceiling: spend no more than the amount in a period.
 * - `savings_balance` — a destination: accumulate up to the amount, optionally
 *   by `targetDate`.
 * - `monthly_contribution` — a cadence: assign the amount every month.
 */
type TargetType = 'spending_limit' | 'savings_balance' | 'monthly_contribution'

// ---------------------------------------------------------------------------
// Core entities
// ---------------------------------------------------------------------------

/**
 * The root container for a plan: one household's budget.
 *
 * Accounts, category groups and payees all belong to exactly one budget, and a
 * single store may hold several budgets side by side.
 */
interface Budget {
  /** Unique identifier. */
  id: Uuid
  /** Human-readable name of the budget. */
  name: string
  /** Currency all amounts in this budget are denominated in. */
  currency: CurrencyCode
}

/**
 * A real-world place money sits: a bank account, a card, a wallet.
 *
 * Accounts hold *actual* money, in contrast to a {@link Category}, which is a
 * plan for money you already have. An account's balance is the sum of its
 * transactions; it is never stored.
 */
interface Account {
  /** Unique identifier. */
  id: Uuid
  /** The {@link Budget} this account belongs to. */
  budgetId: Uuid
  /** Human-readable name, e.g. "Joint Checking". */
  name: string
  /** What kind of container this is. */
  type: AccountType
  /**
   * Whether this account's money feeds the assignable pool.
   *
   * True for budget accounts, false for tracking accounts. Defaults to
   * `type !== 'tracking'` when an account is created.
   */
  onBudget: boolean
}

/**
 * A named bucket of related categories, used to organize the budget view.
 *
 * Groups are purely organizational — no money is assigned to a group — but they
 * are also how a {@link Category} reaches its budget, since categories store
 * only a `groupId`.
 */
interface CategoryGroup {
  /** Unique identifier. */
  id: Uuid
  /** The {@link Budget} this group belongs to. */
  budgetId: Uuid
  /** Group name, e.g. "Housing", "Transportation". */
  name: string
  /** Display order among the groups of a budget; ascending. */
  sortOrder: number
}

/**
 * An envelope: a named purpose you assign money to.
 *
 * A category has no stored balance. Its assigned / activity / available figures
 * are computed per {@link Month} from {@link Assignment} and
 * {@link Transaction} records, and unspent money carries forward into the next
 * month.
 */
interface Category {
  /** Unique identifier. */
  id: Uuid
  /** The {@link CategoryGroup} this category sits in; its budget is the group's. */
  groupId: Uuid
  /** Category name, e.g. "Groceries". */
  name: string
  /** Display order within the group; ascending. */
  sortOrder: number
}

/**
 * Someone money is paid to or received from — a shop, an employer, a person.
 *
 * Payees are labels for reporting and recall; they carry no balance of their
 * own and are optional on a transaction.
 */
interface Payee {
  /** Unique identifier. */
  id: Uuid
  /** The {@link Budget} this payee belongs to. */
  budgetId: Uuid
  /** Payee name, e.g. "Corner Market". */
  name: string
}

/**
 * A single movement of money in or out of an {@link Account}.
 *
 * Transactions are the only record of what actually happened; every balance in
 * the app is derived from them. The `amount` sign says which direction the money
 * moved: positive is an inflow, negative is an outflow.
 */
interface Transaction {
  /** Unique identifier. */
  id: Uuid
  /** The {@link Account} the money moved in or out of. */
  accountId: Uuid
  /**
   * The {@link Category} this spending or income is budgeted against.
   *
   * Null when the transaction is not categorized — notably transfers between
   * two budget accounts, which move money without spending it.
   */
  categoryId: Uuid | null
  /** The {@link Payee} involved, or null when unknown or irrelevant. */
  payeeId: Uuid | null
  /** The calendar date the transaction is budgeted on. */
  date: IsoDate
  /** Signed amount: positive is an inflow, negative is an outflow. */
  amount: Cents
  /** Whether the transaction has been confirmed against the bank. */
  cleared: boolean
  /** Free-text note, or null. */
  memo: string | null
  /** For a transfer, the {@link Account} on the other side; otherwise null. */
  transferAccountId: Uuid | null
}

/**
 * Money placed into a {@link Category} for one {@link Month}.
 *
 * This is the "Assigned" column of the budget view, and the act of budgeting
 * itself: assigning reduces Ready to Assign and raises the category's available
 * balance. There is at most one assignment per category per month.
 */
interface Assignment {
  /** Unique identifier. */
  id: Uuid
  /** The {@link Category} receiving the money. */
  categoryId: Uuid
  /** The budgeting month this assignment applies to. */
  month: Month
  /** Amount assigned; normally positive, negative when pulling money back out. */
  amount: Cents
}

/**
 * A goal attached to a {@link Category}, describing what "funded" means for it.
 *
 * Targets are a plan, not money: they never move funds, they only give the UI
 * and reports something to measure assignments against. A category has at most
 * one target.
 */
interface Target {
  /** Unique identifier. */
  id: Uuid
  /** The {@link Category} this goal belongs to. */
  categoryId: Uuid
  /** How the amount should be interpreted. */
  type: TargetType
  /** The goal amount. */
  amount: Cents
  /** Deadline for reaching the goal, or null if it has no end date. */
  targetDate: IsoDate | null
}

/**
 * A cached snapshot of a {@link Budget}'s closing position for one
 * {@link Month}.
 *
 * Envelope budgeting carries balances forward, so a month's opening figures are
 * the previous month's closing figures. Storing the close makes moving between
 * months a lookup instead of a replay of all history. It is derived data: it can
 * always be recomputed from transactions and assignments.
 */
interface MonthSummary {
  /** Unique identifier. */
  id: Uuid
  /** The {@link Budget} this summary describes. */
  budgetId: Uuid
  /** The month being closed out. */
  month: Month
  /** Ready to Assign — the unassigned pool — at the end of the month. */
  closingRTA: Cents
  /** Available balance at end of month, keyed by {@link Category} id. */
  categoryBalances: Record<Uuid, Cents>
  /** When this summary was last recomputed. */
  updatedAt: IsoDateTime
}

// ---------------------------------------------------------------------------
// Interchange format
// ---------------------------------------------------------------------------

/**
 * One budget and everything belonging to it, flattened for transfer.
 *
 * Relationships stay as IDs rather than nesting, so each array is the full set
 * of that entity for the budget and can be loaded independently.
 */
interface ExportedBudget {
  /** The budget itself. */
  budget: Budget
  /** Every account in the budget. */
  accounts: Account[]
  /** Every category group in the budget. */
  categoryGroups: CategoryGroup[]
  /** Every category, across all of the budget's groups. */
  categories: Category[]
  /** Every payee in the budget. */
  payees: Payee[]
  /** Every transaction, across all of the budget's accounts. */
  transactions: Transaction[]
  /** Every category target in the budget. */
  targets: Target[]
  /** Every monthly assignment in the budget. */
  assignments: Assignment[]
  /** Cached month closings; derived, and safe to drop and recompute. */
  monthSummaries: MonthSummary[]
}

/**
 * The portable JSON document the CLI and the webapp use to hand data to each
 * other.
 *
 * This is the project's interchange format: a whole store serialized, exported
 * by one module and imported by the other, independent of how either side
 * persists data (SQLite on the CLI, browser storage in the webapp).
 */
interface StoreExportData {
  /** Version of the export envelope itself; currently `'1.0'`. */
  version: string
  /** Version of the store schema the data was written against. */
  schemaVersion: number
  /** When the export was taken. */
  exportedAt: IsoDateTime
  /** The exported budgets, each with all of its data. */
  budgets: ExportedBudget[]
}
